services:
  qdrantdb:
    image: qdrant/qdrant
    expose:
      - 6333
      - 6334
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    
  server:
    build:
      context: .
    ports:
      - 8501:8501
    depends_on:
      - qdrantdb
    env_file:
      - .env
